#  Database
spring.datasource.url=jdbc:postgresql://localhost:5432/flowcare
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

#  JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=false

#  Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.repair-on-migrate=true
spring.flyway.ignore-migration-patterns=*:missing

#  JWT
jwt.secret=${JWT_SECRET}
jwt.expiration-ms=86400000

#  File Storage
file.storage.location=uploads
file.max-id-image-size-bytes=5242880
file.max-attachment-size-bytes=10485760

#  Multipart
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=15MB

# Quartz Scheduler
spring.quartz.job-store-type=jdbc
spring.quartz.jdbc.initialize-schema=always
spring.quartz.overwrite-existing-jobs=true
spring.quartz.properties.org.quartz.jobStore.useProperties=true
spring.quartz.properties.org.quartz.jobStore.driverDelegateClass=org.quartz.impl.jdbcjobstore.PostgreSQLDelegate
# Cleanup job schedule (cron expression) and timezone
app.cleanup.cron=0 0 2 * * ?
app.cleanup.timezone=Asia/Muscat

# Swagger /OpenApi
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha
springdoc.swagger-ui.try-it-out-enabled=true
springdoc.swagger-ui.filter=true

logging.level.org.springframework=DEBUG
logging.level.com.rihal=DEBUG

app.base-url=http://localhost:8080

